# Generated by Django 3.1.3 on 2022-08-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_auto_20220818_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='../media/default.png', upload_to='post_pics'),
        ),
    ]
